name: 'tameshi'
description: 'tameshi'
branding:
  icon: moon
  color: gray-dark
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: true
runs:
  using: 'node12'
  main: './index.js'
