name: LGTM
on:
issue_comment:
  types: [created]
pull_request_review:
  types: [submitted]
pull_request_review_comment:
  types: [created]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: LGTM
        uses: kazu-2020/githun-actions-sample
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
