on:
  push:
  workflow_dispatch:

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: LGTM
        uses: kazu-2020/githun-actions-sample@tameshi1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
